name: Sync CSI Repos with Upstream

on:
  schedule:
    # Every day at 3:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup GitHub CLI auth for git
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          gh auth status
          gh auth setup-git

      - name: Setup Git identity
        run: |
          git config --global user.email "derek.su@suse.com"
          git config --global user.name "Derek Su"

      - name: Sync Repos
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          bash ./scripts/sync-csi-repos-with-upstream.sh